language: bash

sudo: required
dist: trusty
services: docker

matrix:
  include:
    - os: linux
      name: "linux"
    - os: linux-ppc64le
      name: "linux-ppc64le"

before_script:
 - ./docker/build-builder

script:
 - ./docker/build-pb --check --verbose --configure-opts "--enable-platform-arm64 --enable-platform-powerpc"
